[project]
name = "pyminitel"
version = "0.5.0"
authors = [
    { name="Xenoth", email="xenothvalack@gmail.com" },
]
description = "Minitel Python module"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "aenum",
    "pyserial",
    "pillow",
    "redis",
    "nltk"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pyminitel = ["py.typed"]

[project.urls]
Homepage = "https://github.com/Xenoth/pyminitel"
Issues = "https://github.com/Xenoth/pyminitel/issues"