from pyminitel.minitel import Minitel
from pyminitel.mode import Mode
from pyminitel.attributes import *
import time

minitel = Minitel(port='/dev/tty.usbserial-2', mode=Mode.VIDEOTEX, bauderate=Minitel.Bauderate.BAUDS_1200)
# minitel.setConnectorBauderate(Minitel.Bauderate.BAUDS_4800, Minitel.Bauderate.BAUDS_4800)
minitel.clear()
minitel.setScreenRollMode()
minitel.setZoneAttributes(highlight=True)
minitel.setTextAttributes(double_height=True, double_width=False)
minitel.print("Without word breaking:")
minitel.setZoneAttributes(highlight=False)
minitel.newLine()
minitel.newLine()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(text='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam.')
minitel.newLine()
minitel.newLine()
minitel.print('Lorem ipsum dolor sit amet, consectetur_adipiscing_elit._Sed_non_risus._Suspendisse_lectus_tortor,_dignissim_sit_amet._Consectetur_adipiscing_elit._Sed_non_risus._Suspendisse_lectus_tortor,_dignissim_sit_amet.')
minitel.setTextAttributes(color=CharacterColor.WHITE)
minitel.newLine()
minitel.newLine()
minitel.newLine()
minitel.newLine()
minitel.setZoneAttributes(highlight=True)
minitel.print("With word breaking:")
minitel.setZoneAttributes(highlight=False)
minitel.newLine()
minitel.newLine()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(break_word=True, text='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. AAND  DOTS.......')
minitel.setTextAttributes(color=CharacterColor.WHITE)
minitel.newLine()
minitel.newLine()
minitel.newLine()
minitel.newLine()
minitel.setTextAttributes(color=CharacterColor.BLACK)
minitel.setZoneAttributes(highlight=True, color=BackgroundColor.WHITE)
minitel.print("Special character interpretation '\\r & \\n':")
minitel.setZoneAttributes(highlight=False, color=BackgroundColor.BLACK)
minitel.newLine()
minitel.newLine()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(text='Lorem ipsum dolor sit amet, \nconsectetur adipiscing elit. Sed non risus. \n\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. AAND  DOTS.......\rPOUET RETURN CARIAGE__ ___ _')
minitel.setTextAttributes(color=CharacterColor.WHITE)
minitel.Beep()
# minitel.setConnectorBauderate(Minitel.Bauderate.BAUDS_1200, Minitel.Bauderate.BAUDS_1200)
time.sleep(10)