from pyminitel.minitel import Minitel
from pyminitel.attributes import *

minitel = Minitel(port='/dev/tty.usbserial-2')

minitel.clear()
minitel.setScreenRollMode()

minitel.Beep()

while 1:
    minitel.setZoneAttributes(color=BackgroundColor.BLACK)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.BLUE)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.RED)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.MAGENTA)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.GREEN)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.CYAN)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.YELLOW)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.WHITE)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.YELLOW)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.CYAN)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.GREEN)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.MAGENTA)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.RED)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
    minitel.setZoneAttributes(color=BackgroundColor.BLUE)
    minitel.layout.fillLine()
    minitel.layout.cariageReturn()
    minitel.layout.moveCursorDown()
