from pyminitel.minitel import Minitel
from pyminitel.attributs import *
from pyminitel.layout import Layout
import time

minitel = Minitel(port='/dev/tty.usbserial-2')
l = Layout(minitel.din)
minitel.setScreenRollMode()

l.Clear()
minitel.setZoneAttributes(highlight=True)
minitel.print("Without word breaking:")
minitel.setZoneAttributes(highlight=False)
l.MoveCursorDown(2)
l.CariageReturn()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(text='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam.')
l.MoveCursorDown(2)
l.CariageReturn()
minitel.print('Lorem ipsum dolor sit amet, consectetur_adipiscing_elit._Sed_non_risus._Suspendisse_lectus_tortor,_dignissim_sit_amet.')
minitel.setTextAttributes(color=CharacterColor.WHITE)
l.MoveCursorDown(4)
l.CariageReturn()
minitel.setZoneAttributes(highlight=True)
minitel.print("With word breaking:")
minitel.setZoneAttributes(highlight=False)
l.MoveCursorDown(2)
l.CariageReturn()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(break_word=True, text='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Et  POINT.......')
minitel.setTextAttributes(color=CharacterColor.WHITE)
l.MoveCursorDown(4)
l.CariageReturn()
minitel.setTextAttributes(color=CharacterColor.BLACK)
minitel.setZoneAttributes(highlight=True, color=BackgroundColor.WHITE)
minitel.print("Special character interpretation '\\r & \\n':")
minitel.setZoneAttributes(highlight=False, color=BackgroundColor.BLACK)
l.MoveCursorDown(2)
l.CariageReturn()
minitel.setTextAttributes(color=CharacterColor.YELLOW)
minitel.print(text='Lorem ipsum dolor sit amet, \nconsectetur adipiscing elit. Sed non risus. \n\nSuspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Et  POINT.......\rPOUET RETURN CARIAGE______')
minitel.setTextAttributes(color=CharacterColor.WHITE)
minitel.Beep()

time.sleep(10)